services:
  # The MongoDB Database (Using 4.4 to fix the EC2 restart crash)
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 256M

  # Redis (Required for MuchTodo caching)
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M

  # Your Go Backend
  backend:
    build: .
    container_name: much-to-do-api
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - DB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis:6379
      - PORT=8080
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 350M

volumes:
  mongo_data: